/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as ProjectsOutreachRouteImport } from './routes/projects-outreach'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OutreachSlugRouteImport } from './routes/outreach.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as UpdatesSlugRouteImport } from './routes/updates.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOutreachRoute = ProjectsOutreachRouteImport.update({
  id: '/projects-outreach',
  path: '/projects-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OutreachSlugRoute = OutreachSlugRouteImport.update({
  id: '/outreach/$slug',
  path: '/outreach/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UpdatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/our-work': typeof OurWorkRoute
  '/projects-outreach': typeof ProjectsOutreachRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/outreach/$slug': typeof OutreachSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/our-work': typeof OurWorkRoute
  '/projects-outreach': typeof ProjectsOutreachRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/outreach/$slug': typeof OutreachSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/our-work': typeof OurWorkRoute
  '/projects-outreach': typeof ProjectsOutreachRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/outreach/$slug': typeof OutreachSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/our-work'
    | '/projects-outreach'
    | '/upcoming'
    | '/updates'
    | '/admin'
    | '/outreach/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/our-work'
    | '/projects-outreach'
    | '/upcoming'
    | '/updates'
    | '/admin'
    | '/outreach/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/get-involved'
    | '/our-work'
    | '/projects-outreach'
    | '/upcoming'
    | '/updates'
    | '/_authenticated/admin'
    | '/outreach/$slug'
    | '/projects/$slug'
    | '/updates/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  OurWorkRoute: typeof OurWorkRoute
  ProjectsOutreachRoute: typeof ProjectsOutreachRoute
  UpcomingRoute: typeof UpcomingRoute
  UpdatesRoute: typeof UpdatesRouteWithChildren
  OutreachSlugRoute: typeof OutreachSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-outreach': {
      id: '/projects-outreach'
      path: '/projects-outreach'
      fullPath: '/projects-outreach'
      preLoaderRoute: typeof ProjectsOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/outreach/$slug': {
      id: '/outreach/$slug'
      path: '/outreach/$slug'
      fullPath: '/outreach/$slug'
      preLoaderRoute: typeof OutreachSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof UpdatesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UpdatesRouteChildren {
  UpdatesSlugRoute: typeof UpdatesSlugRoute
}

const UpdatesRouteChildren: UpdatesRouteChildren = {
  UpdatesSlugRoute: UpdatesSlugRoute,
}

const UpdatesRouteWithChildren =
  UpdatesRoute._addFileChildren(UpdatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  OurWorkRoute: OurWorkRoute,
  ProjectsOutreachRoute: ProjectsOutreachRoute,
  UpcomingRoute: UpcomingRoute,
  UpdatesRoute: UpdatesRouteWithChildren,
  OutreachSlugRoute: OutreachSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
